/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModels.ChiTietDichVu;
import DomainModels.ChiTietHoaDon;
import DomainModels.ChuTro;
import DomainModels.DichVu;
import DomainModels.HoaDon;
import Service.IServiceHoaDon;
import Service.impl.ServiceHoaDonImpl;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewHoaDon extends javax.swing.JFrame {

    private IServiceHoaDon svH = new ServiceHoaDonImpl();
    private DefaultTableModel dtm;

    /**
     * Creates new form ViewHoaDon
     */
    public ViewHoaDon() {
        initComponents();
        loadTablebHd(svH.listHoaDon());
        //loadTablebCthd(svH.listCthd());
        loadTablebDv(svH.listCtdv());

    }

    public void loadTablebHd(List<HoaDon> list) {
        dtm = (DefaultTableModel) tbHd.getModel();
        dtm.setRowCount(0);
        for (HoaDon hd : list) {
            dtm.addRow(new Object[]{
                dtm.getRowCount() + 1, hd.getMa(), hd.getNgayTao(), hd.getChuTro().getTen(), hd.htTrangThai()
            });
        }
    }

    public void loadTablebCthd(List<ChiTietHoaDon> list) {
        dtm = (DefaultTableModel) tbCthd.getModel();
        dtm.setRowCount(0);
        for (ChiTietHoaDon c : list) {
            dtm.addRow(new Object[]{
                dtm.getRowCount() + 1, c.getHoaDon().getMa(), c.getCtdv().getMa(),
                c.getNgayTao(), c.getNgaySua(), c.getTongTien(), c.htTrangThai()
            });
        }
    }

    public void loadTablebDv(List<ChiTietDichVu> list) {
        dtm = (DefaultTableModel) tbDv.getModel();
        dtm.setRowCount(0);
        for (ChiTietDichVu d : list) {
            dtm.addRow(new Object[]{
                dtm.getRowCount() + 1, d.getMa(), d.getPhong().getTen(),
                d.getPhong().getGia(), d.getDien().getThanhTien(),
                d.getNuoc().getThanhTien(), d.getDichVu().getThanhTien(), d.getNgayTao(), d.getNgaySua()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btTaoHd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCthd = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDv = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtHdMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCtdvMa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btThanhToan = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        btGhiNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btTaoHd.setText("Tạo hóa đơn");
        btTaoHd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoHdActionPerformed(evt);
            }
        });

        tbHd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT ", "Mã ", "Ngày tạo", "Tên chủ trọ", "Tình trạng"
            }
        ));
        tbHd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHd);

        tbCthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HĐ", "Mã CTDV", "Ngày Tạo ", "Ngày thanh toán", "Tổng tiền ", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(tbCthd);

        jLabel1.setText("Hóa đơn khách hàng");

        jLabel2.setText("Dịch vụ");

        tbDv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Phòng", "TIền phòng", "Tiền điện", "Tiền nước", "Tiền dịch vụ", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        tbDv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDvMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDv);

        jLabel3.setText("Mã HĐ");

        jLabel4.setText("Mã Ctdv");

        jLabel5.setText("Tổng tiền ");

        btThanhToan.setText("Thanh toán");
        btThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThanhToanActionPerformed(evt);
            }
        });

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        btGhiNo.setText("Ghi nợ");
        btGhiNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGhiNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btTaoHd)
                                    .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCtdvMa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHdMa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btThanhToan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(btGhiNo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btTaoHd)
                                .addGap(66, 66, 66)
                                .addComponent(btBack))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtHdMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCtdvMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btThanhToan)
                            .addComponent(btGhiNo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTaoHdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoHdActionPerformed
        // TODO add your handling code here:
        HoaDon hd = new HoaDon();
        ChuTro ct = new ChuTro();
        String ma = "HD" + svH.genMaHD();
        Date ngayTao = java.util.Calendar.getInstance().getTime();
        UUID idCt = svH.findByIdCt("chien");
        ct.setId(idCt);
        int tinhTrang = 0;
        hd.setMa(ma);
        hd.setNgayTao(ngayTao);
        hd.setChuTro(ct);
        hd.setTinhTrang(tinhTrang);
        svH.addHd(hd);
        loadTablebHd(svH.listHoaDon());
    }//GEN-LAST:event_btTaoHdActionPerformed

    private void tbHdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHdMouseClicked
        // TODO add your handling code here:
        int index = tbHd.getSelectedRow();
        String ma = tbHd.getValueAt(index, 1).toString();
        txtHdMa.setText(ma);
        loadTablebCthd(svH.listCthd(ma));
    }//GEN-LAST:event_tbHdMouseClicked

    private void tbDvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDvMouseClicked
        // TODO add your handling code here:
        int index = tbDv.getSelectedRow();
        String ma = tbDv.getValueAt(index, 1).toString();
        txtCtdvMa.setText(ma);
        double tienPhong = (double) tbDv.getValueAt(index, 3);
        double tienDien = (double) tbDv.getValueAt(index, 4);
        double tienNuoc = (double) tbDv.getValueAt(index, 5);
        double tienDv = (double) tbDv.getValueAt(index, 6);
        double tongTien = tienPhong + tienDien + tienNuoc + tienDv;
        txtTongTien.setText(String.valueOf(tongTien));
    }//GEN-LAST:event_tbDvMouseClicked

    private void btThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThanhToanActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDon c = new ChiTietHoaDon();
        int index = tbHd.getSelectedRow();
        HoaDon hd = svH.listHoaDon().get(index);
        hd.setTinhTrang(1);
        svH.addHd(hd);
        loadTablebHd(svH.listHoaDon());
        ChiTietDichVu d = new ChiTietDichVu();
        String maHd = txtHdMa.getText();
        String maCtdv = txtCtdvMa.getText();
        UUID idHd = svH.findByIdHd(maHd);
        UUID idCtdv = svH.findByIdDv(maCtdv);
        double tongTien = Double.parseDouble(txtTongTien.getText());
        c.setIdHd(idHd);
        c.setIdCtdv(idCtdv);
        c.setNgayTao(java.util.Calendar.getInstance().getTime());
        c.setNgaySua(java.util.Calendar.getInstance().getTime());
        c.setTrangThai(1);
        c.setTongTien(tongTien);
        svH.addHdct(c);
        loadTablebCthd(svH.listCthd(maHd));
    }//GEN-LAST:event_btThanhToanActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        ViewChuTro vct = new ViewChuTro();
        vct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btBackActionPerformed

    private void btGhiNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGhiNoActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDon c = new ChiTietHoaDon();
        int index = tbHd.getSelectedRow();
        HoaDon hd = svH.listHoaDon().get(index);
        hd.setTinhTrang(0);
        svH.addHd(hd);
        loadTablebHd(svH.listHoaDon());
        ChiTietDichVu d = new ChiTietDichVu();
        String maHd = txtHdMa.getText();
        String maCtdv = txtCtdvMa.getText();
        UUID idHd = svH.findByIdHd(maHd);
        UUID idCtdv = svH.findByIdDv(maCtdv);
        double tongTien = Double.parseDouble(txtTongTien.getText());
        c.setIdHd(idHd);
        c.setIdCtdv(idCtdv);
        c.setNgayTao(java.util.Calendar.getInstance().getTime());
        c.setNgaySua(java.util.Calendar.getInstance().getTime());
        c.setTrangThai(0);
        c.setTongTien(tongTien);
        svH.addHdct(c);
        loadTablebCthd(svH.listCthd(maHd));
    }//GEN-LAST:event_btGhiNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btGhiNo;
    private javax.swing.JButton btTaoHd;
    private javax.swing.JButton btThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbCthd;
    private javax.swing.JTable tbDv;
    private javax.swing.JTable tbHd;
    private javax.swing.JTextField txtCtdvMa;
    private javax.swing.JTextField txtHdMa;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
