/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModels.KhachHang;

/**
 *
 * @author admin
 */
public class ViewChuTro extends javax.swing.JFrame {

    /**
     * Creates new form ViewChuTro
     */
    public ViewChuTro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btQltd = new javax.swing.JButton();
        btQlpt = new javax.swing.JButton();
        btQldv = new javax.swing.JButton();
        btQltn = new javax.swing.JButton();
        btQlkh = new javax.swing.JButton();
        btThongKe = new javax.swing.JButton();
        btHopDong = new javax.swing.JButton();
        btQlhd = new javax.swing.JButton();
        btQLCtdv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Danh sách chức năng");

        btQltd.setText("Quản lý tiền điện");
        btQltd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQltdActionPerformed(evt);
            }
        });

        btQlpt.setText("Quản lý phòng trọ");
        btQlpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQlptActionPerformed(evt);
            }
        });

        btQldv.setText("Quản lý dịch vụ");
        btQldv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQldvActionPerformed(evt);
            }
        });

        btQltn.setText("Quản lý tiền nước");
        btQltn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQltnActionPerformed(evt);
            }
        });

        btQlkh.setText("Quản lý khách hàng");
        btQlkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQlkhActionPerformed(evt);
            }
        });

        btThongKe.setText("Thống kê");
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });

        btHopDong.setText("Hợp đồng");
        btHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHopDongActionPerformed(evt);
            }
        });

        btQlhd.setText("Quản lý hóa đơn");
        btQlhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQlhdActionPerformed(evt);
            }
        });

        btQLCtdv.setText("Quản lý CTDV");
        btQLCtdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLCtdvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btQlpt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQLCtdv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btQltd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btQltn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btQlkh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btQlhd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btQldv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQltd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQlpt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQltn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQldv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQlkh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQlhd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQLCtdv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQLCtdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLCtdvActionPerformed
        // TODO add your handling code here:
        ViewQldv qldv = new ViewQldv();
        qldv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQLCtdvActionPerformed

    private void btQlptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQlptActionPerformed
        // TODO add your handling code here:
        ViewPhong vp = new ViewPhong();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQlptActionPerformed

    private void btQltdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQltdActionPerformed
        // TODO add your handling code here:
        ViewDien vp = new ViewDien();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQltdActionPerformed

    private void btQltnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQltnActionPerformed
        // TODO add your handling code here:
        ViewNuoc vp = new ViewNuoc();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQltnActionPerformed

    private void btQldvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQldvActionPerformed
        // TODO add your handling code here:
        ViewDichVu vp = new ViewDichVu();
        vp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQldvActionPerformed

    private void btQlhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQlhdActionPerformed
        // TODO add your handling code here:
        ViewHoaDon vhd = new ViewHoaDon();
        vhd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQlhdActionPerformed

    private void btHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHopDongActionPerformed
        // TODO add your handling code here:
        ViewHopDong vhd = new ViewHopDong();
        vhd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHopDongActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed
        // TODO add your handling code here:
        ViewThongKe vtk = new ViewThongKe();
        vtk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btThongKeActionPerformed

    private void btQlkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQlkhActionPerformed
        // TODO add your handling code here:
        ViewKhachHang vkd = new ViewKhachHang();
        vkd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQlkhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewChuTro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewChuTro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHopDong;
    private javax.swing.JButton btQLCtdv;
    private javax.swing.JButton btQldv;
    private javax.swing.JButton btQlhd;
    private javax.swing.JButton btQlkh;
    private javax.swing.JButton btQlpt;
    private javax.swing.JButton btQltd;
    private javax.swing.JButton btQltn;
    private javax.swing.JButton btThongKe;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
